/*
 * Silicon Laboratories Confidential
 * Copyright 2011 Silicon Laboratories, Inc.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!
 */

#include "radio.h"


//SEGMENT_VARIABLE( Si446xChipPend, U8, SEG_BDATA );
//SBIT(Si446xWUTPend,Si446xChipPend,0);
//SBIT(Si446xLowBattPend,Si446xChipPend,1);
//SBIT(Si446xChipReadyPend,Si446xChipPend,2);
//SBIT(Si446xCmdErrPend,Si446xChipPend,2);
//SBIT(Si446xStateChangePend,Si446xChipPend,2);
//SBIT(Si446xFifoUnderflowOverflowErrorPend,Si446xChipPend,2);
//SEGMENT_VARIABLE( Si446xPhPend, U8, SEG_BDATA );
//SEGMENT_VARIABLE( Si446xModemPend, U8, SEG_BDATA );

#define Si446xWUTPend                           Si446xPhPend0
#define Si446xLowBattPend                       Si446xPhPend1
#define Si446xChipReadyPend                     Si446xPhPend2
#define Si446xCmdErrPend                        Si446xPhPend3
#define Si446xStateChangePend                   Si446xPhPend4
#define Si446xFifoUnderflowOverflowErrorPend    Si446xPhPend5
#define Si446xDummyPhPend6                      Si446xPhPend6
#define Si446xDummyPhPend7                      Si446xPhPend7

#define Si446xSyncDetectPend                    Si446xModemPend0
#define Si446xPreambleDetectPend                Si446xModemPend1
#define Si446xInvalidPreamblePend               Si446xModemPend2
#define Si446xRssiPend                          Si446xModemPend3
#define Si446xRssiJumpPend                      Si446xModemPend4
#define Si446xInvalidSyncPend                   Si446xModemPend5
#define Si446xDummyModemPend6                   Si446xModemPend6
#define Si446xDummyModemPend7                   Si446xModemPend7

#define Si446xRxFifoAlmostFullPend              Si446xChipPend0
#define Si446xTxFifoAlmostEmptyPend             Si446xChipPend1
#define Si446xCrc16ErrorPend                    Si446xChipPend2
#define Si446xCrc32ErrorPend                    Si446xChipPend3
#define Si446xPacketRxPend                      Si446xChipPend4
#define Si446xPacketSentPend                    Si446xChipPend5
#define Si446xFilterMissPend                    Si446xChipPend6
#define Si446xFilterMatchPend                   Si446xChipPend7

/*!
 * Do NOT use SEG_BDATA as that is not understood by SDCC!
 * Use BITS, WRITE_TO_BIT_ARRAY and READ_FROM_BIT_ARRAY instead to allocate and
 * handle bit arrays in a convenient way.
 *
 * Allocate all 8bits if WRITE_TO_BIT_ARRAY and READ_FROM_BIT_ARRAY macros
 * are to be used. Otherwise these macros would read/write bits that are
 * placed within that byte by the linker.
 */

unsigned char Si446xPhPend0;
unsigned char Si446xPhPend1;
unsigned char Si446xPhPend2;
unsigned char Si446xPhPend3;
unsigned char Si446xPhPend4;
unsigned char Si446xPhPend5;
unsigned char Si446xPhPend6;
unsigned char Si446xPhPend7;

unsigned char Si446xModemPend0;
unsigned char Si446xModemPend1;
unsigned char Si446xModemPend2;
unsigned char Si446xModemPend3;
unsigned char Si446xModemPend4;
unsigned char Si446xModemPend5;
unsigned char Si446xModemPend6;
unsigned char Si446xModemPend7;

unsigned char Si446xChipPend0;
unsigned char Si446xChipPend1;
unsigned char Si446xChipPend2;
unsigned char Si446xChipPend3;
unsigned char Si446xChipPend4;
unsigned char Si446xChipPend5;
unsigned char Si446xChipPend6;
unsigned char Si446xChipPend7;

/*!
 * This function is used to handle the assertion of nIRQ of the si446x chip.
 *
 * @note This function can take up to 6 ms depending on the startup time of the
 * si446x chip.
 *
 */
void si446x_nirq_process(void)
{
#ifdef SI446X_USER_CONFIG_USE_FRR_ABC_FOR_NIRQ

    uint8_t pendBits[3];

    si446x_frr_read();
#else
    si446x_get_int_status(0, 0, 0);
//    Si446xPhPend = Si446xCmd.GET_INT_STATUS.PH_PEND;
//    Si446xModemPend = Si446xCmd.GET_INT_STATUS.MODEM_PEND;
//    Si446xChipPend = Si446xCmd.GET_INT_STATUS.CHIP_PEND;


    Si446xPhPend0 = Si446xCmd.GET_INT_STATUS.PH_PEND & 0x01; \
		Si446xPhPend1 = Si446xCmd.GET_INT_STATUS.PH_PEND & 0x02; \
		Si446xPhPend2 = Si446xCmd.GET_INT_STATUS.PH_PEND & 0x04; \
		Si446xPhPend3 = Si446xCmd.GET_INT_STATUS.PH_PEND & 0x08; \
		Si446xPhPend4 = Si446xCmd.GET_INT_STATUS.PH_PEND & 0x10; \
		Si446xPhPend5 = Si446xCmd.GET_INT_STATUS.PH_PEND & 0x20; \
		Si446xPhPend6 = Si446xCmd.GET_INT_STATUS.PH_PEND & 0x40; \
		Si446xPhPend7 = Si446xCmd.GET_INT_STATUS.PH_PEND & 0x80;
	Si446xModemPend0 = Si446xCmd.GET_INT_STATUS.MODEM_PEND & 0x01; \
		Si446xModemPend1 = Si446xCmd.GET_INT_STATUS.MODEM_PEND & 0x02; \
		Si446xModemPend2 = Si446xCmd.GET_INT_STATUS.MODEM_PEND & 0x04; \
		Si446xModemPend3 = Si446xCmd.GET_INT_STATUS.MODEM_PEND & 0x08; \
		Si446xModemPend4 = Si446xCmd.GET_INT_STATUS.MODEM_PEND & 0x10; \
		Si446xModemPend5 = Si446xCmd.GET_INT_STATUS.MODEM_PEND & 0x20; \
		Si446xModemPend6 = Si446xCmd.GET_INT_STATUS.MODEM_PEND & 0x40; \
		Si446xModemPend7 = Si446xCmd.GET_INT_STATUS.MODEM_PEND & 0x80;
	Si446xChipPend0 = Si446xCmd.GET_INT_STATUS.CHIP_PEND & 0x01; \
		Si446xChipPend1 = Si446xCmd.GET_INT_STATUS.CHIP_PEND & 0x02; \
		Si446xChipPend2 = Si446xCmd.GET_INT_STATUS.CHIP_PEND & 0x04; \
		Si446xChipPend3 = Si446xCmd.GET_INT_STATUS.CHIP_PEND & 0x08; \
		Si446xChipPend4 = Si446xCmd.GET_INT_STATUS.CHIP_PEND & 0x10; \
		Si446xChipPend5 = Si446xCmd.GET_INT_STATUS.CHIP_PEND & 0x20; \
		Si446xChipPend6 = Si446xCmd.GET_INT_STATUS.CHIP_PEND & 0x40; \
		Si446xChipPend7 = Si446xCmd.GET_INT_STATUS.CHIP_PEND & 0x80;
#endif
}

